### ISSUE TITLE
Catppuccin logo dropdown

### ISSUE THREAD

**Issue by yifto** [42Willow/schooltape#47]
### Is your feature request related to a problem?

How can i change catpuccin to a different image?

### Describe the solution you'd like

Make a way to change the image

### Describe alternatives you've considered

tried changing the parts of the code but didn't work

### Would you like to contribute code to this feature?

- [X] I'm interested in contributing code to this feature

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42Willow** [comment]
I was planning on doing this but I haven't gotten around to it yet. Here's a snippet you can use and alter in the meantime though.

https://gist.github.com/42Willow/27043ca58c5dca1c7a5a1140d8f79e54

**Comment by 42Willow** [comment]
Duplicate and tracked by #43
