### ISSUE TITLE
QR buttons broken!!!

### ISSUE THREAD

**Issue by JerryTangy** [42Willow/schooltape#52]
### What happened?

i was happily using your schooltape, but all of a sudden, i noticed that the qr code buttons broken!!!!! ::<<<< i would apreecieatte it if this issue can be resolved!!!
otherwise ill dislike your app!!!!
it better be resolved grr

### Version

2.3.5.2.5.4.2v3

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42Willow** [comment]
See #51
