### ISSUE TITLE
`modern-icons` Font sanitisation error

### ISSUE THREAD

**Issue by 42Willow** [42Willow/schooltape#65]
Just tested.
https://fonts.gstatic.com/s/materialiconsround/v100/LDItaoyNOAY6Uewc665JcIzCKsKc_M9flwmP.woff2 downloads the woff 2 file, and https://fonts.googleapis.com/icon?family=Material+Icons works fine aswell. 
I use firefox at home so ye
got a bunch of errors
![Screen Shot 2024-06-04 at 5 40 54 pm](https://github.com/42Willow/schooltape/assets/152151849/91bdf8c4-58fc-4762-a4f9-e42b0443cea0)
![Screen Shot 2024-06-04 at 5 41 32 pm](https://github.com/42Willow/schooltape/assets/152151849/6c781e9a-7380-4452-91ae-70552e2a0e3f)
There are some warnings, but they aren't relevant :))))
I would join the discord but I don't have access to my alt accounts rn :((((

_Originally posted by @Neoskimmer in https://github.com/42Willow/schooltape/issues/64#issuecomment-2146831715_

**Comment by Neoskimmer** [comment]
I contacted you on matrix to make it easier (Does that make it easier?? IDK)

**Comment by 42Willow** [comment]
This was discussed and likely due to a client side memory or other issue. Can't reproduce anywhere else.
